### ISSUE TITLE
请问是否有计划为钉钉机器人提供支持呢？

### ISSUE THREAD

**Issue by oncebeloved** [lkiuyu/DbusSmsForward#4]
你好，你开发的软件用起来很方便，但是美中不足的是："没有对钉钉提供支持"!
请问是否有计划为钉钉机器人提供支持呢？

**Comment by lkiuyu** [comment]
等有空就添加下钉钉机器人支持

**Comment by lkiuyu** [comment]
我刚刚看到有别的大佬fork我的项目把钉钉推送功能给做好了，我直接合并过来发个版本，你下载试试看

**Comment by oncebeloved** [comment]
下载使用了，发现你这缺少secret签名参数，并不能正确推送加签的消息！

**Comment by oncebeloved** [comment]
加签可以参考我以前写的shell，你这项目我没有现成的编译环境，没法修改编译！大佬辛苦了！message_text=$1
message_json='{"msgtype": "text", "text": {"content": "'"${message_text}"'"}}'

access_token=xxxxxxxxxxxx
secret="xxxxxxxxx"

webhook="https://oapi.dingtalk.com/robot/send?access_token=$access_token"

timestamp="$(date +%s%N | cut -b1-13)"

sign=$(printf "${timestamp}\n${secret}" | openssl dgst -binary -sha256 -hmac "${secret}" | base64)
curl "$webhook&timestamp=$timestamp&sign=$sign" \
    -H 'Content-Type: application/json' \
    -d "$message_json";echo "\n"

**Comment by lkiuyu** [comment]
已更改安全校验方式从固定关键词到加签校验，可以试一下最新版
