### ISSUE TITLE
使用内置esim太难了

### ISSUE THREAD

**Issue by woshichenghaibo** [lkiuyu/DbusSmsForward#6]
一直调试不出来

**Comment by lkiuyu** [comment]
这个程序和你使用内置esim还是外置sim没啥关联的，只要你modemManager是正常的应该就能用，使用esim还是外置卡槽是由你系统决定，不过有一点需要注意，410的棒子对电信短信支持并不好，而内置的esim大多都是电信的，不过话说回来，内置的esim不是物联网卡吗，支持收短信吗
