### ISSUE TITLE
不支持自建的TGBot的API

### ISSUE THREAD

**Issue by castula** [lkiuyu/DbusSmsForward#7]
Config中不支持填入自建的API反代地址，希望作者能够提供在DbusSmsForward.dll.config里，这样不加代理的情况才能发送TG通知

![image](https://github.com/lkiuyu/DbusSmsForward/assets/58811486/ab23fdf8-3940-4357-a808-db0ccabd5a99)

**Comment by lkiuyu** [comment]
这个可以有，我看看改一下

**Comment by lkiuyu** [comment]
最新版本已支持自定义代理api

**Comment by castula** [comment]
感谢！这么迅速 😂

**Comment by LaoTzuCN** [comment]
> 感谢！这么迅速 😂

试了一下貌似不行，提示以下：The remote server returned an error: (500) Internal Server Error.

![image](https://github.com/lkiuyu/DbusSmsForward/assets/58811486/8d2072d8-19df-4e09-be89-8e3b1434874f)


配置文件如下：

![image](https://github.com/lkiuyu/DbusSmsForward/assets/58811486/eb11a117-d7eb-4fc8-8a4f-acd9f5ada3b3)


自行测试可行，结果如下：

![image](https://github.com/lkiuyu/DbusSmsForward/assets/58811486/cf5ca5bd-9bdc-47ec-b338-8bc9bf8dafc7)

麻烦兄弟看看是什么问题，难道是我自建的反代问题？但是自行测试是可以的呀
