### ISSUE TITLE
能否增加修改信息模板显示顺序？

### ISSUE THREAD

**Issue by Cxleos** [lkiuyu/DbusSmsForward#8]
默认的文本模板是
标题
电话
时间
内容
这种显示方式在手机的通知提醒中只能看到前三行，后面的内容看不到，必须要打开app才能看。

能否增加个排序功能，
如果将排序设置为
内容
电话
时间
标题
这样在手机上通知就能直接看到短信内容。对验证码消息友好。

**Comment by lkiuyu** [comment]
标题并不是和短信内容在同一个文本段，目前程序对接的几个转发渠道都是有独立的标题设置参数的，排序可以实现，但标题不会动，能自定义排序的为内容、电话和时间

**Comment by lkiuyu** [comment]
不过如果只是想看验证码的话，感觉可以用正则去匹配筛选下验证码，然后直接把验证码塞标题里，这个等我有空搞搞看

**Comment by Cxleos** [comment]
正则也可以的，有排序功能后标题的那几个字长度影响不大，两种方式都比较好，期待

**Comment by lkiuyu** [comment]
已更新短信验证码自动提取到转发标题的功能，可以下载最新版试试

**Comment by Cxleos** [comment]
好的,大佬中秋国庆愉快,稍后我体验下

**Comment by Cxleos** [comment]
已使用新版，验证码匹配的蛮好，大佬辛苦了

提供一份我自己的开机启动服务

DbusSmsForward程序和config解压在home目录中后

nano /etc/systemd/system/DbusSmsForward.service
粘贴以下内容
[Unit]
Description=DbusSmsForward
After=network.target

[Service]
Type=simple
WorkingDirectory=/home/
ExecStart=/home/DbusSmsForward -fW

[Install]
WantedBy=multi-user.target

//其中WorkingDirectory必须,否则无法开机启动,[ -fW]可替换为其他转发模式

chmod 777 DbusSmsForward.service
systemctl start DbusSmsForward.service     //设置好转发配置后再启动
systemctl status DbusSmsForward.service    //检查一下是否启动成功
systemctl enable DbusSmsForward.service    //设置开机启动

同理,如果要开机启动[smsmanager]   在ExecStart修改一下ExecStart=/home/smsmanager   即可

**Comment by lkiuyu** [comment]
刚刚完善了下，可以试试最新版，验证码关键词扔到配置文件了（使用±作为间隔），验证码来源也可以识别短信末尾的了

**Comment by Cxleos** [comment]
刚刚试用了最新版本,正则表达式在特定场景下有点问题,这里会匹配不符合要求的内容并截断
![image](https://github.com/lkiuyu/DbusSmsForward/assets/23045333/a6c5d8a1-c587-457c-98ff-5f7423ab4d49)


我尝试替换成  (?<!\w)[A-Za-z0-9]{4,7}(?!\w) 
![image](https://github.com/lkiuyu/DbusSmsForward/assets/23045333/99c0d377-e3e6-4660-b005-ee11c5513e6a)

**Comment by Cxleos** [comment]
【京东】7526303
短信转发
发信电话:
时间:2023-09-29 19:21:03 
短信内容:【京东】请确认本人操作，切勿泄露给他人。短信登录验证码：563716。京东工作人员绝不会索取此验证码。(本短信由阿里小号接收，来自1063012247526303)

类似这样的短信就会匹配出问题,是否可以把正则也放到配置文件里去呢?

**Comment by lkiuyu** [comment]
比较奇怪的是，我在线测试使用的正则，实际不会出现匹配多个的情况
![image](https://github.com/lkiuyu/DbusSmsForward/assets/8980816/90bddd5b-2291-4283-9f52-8e73262a5120)
我得排查排查别的原因

**Comment by Cxleos** [comment]
抱歉,我的问题,我测试正则时丢了最后的\b    (?<=\b[\p{L}\p{N}]{0,1000})[A-Za-z0-9]{4,7}**\b**

在线测试确实正常的,不知道问题出在哪

【京东】7526303
短信转发
发信电话:
时间:2023-09-29 21:33:45 
短信内容:【京东】请确认本人操作，切勿泄露给他人。短信登录验证码：879933。京东工作人员绝不会索取此验证码。(本短信由阿里小号接收，来自1063012247526303)

**Comment by lkiuyu** [comment]
刚刚更新完善了下正则，你试试重新下一下最新版程序

**Comment by lkiuyu** [comment]
不对，还是不太行，估计还得改改

**Comment by Cxleos** [comment]
我用发布文件夹里新打的包测试还是一样,这个场景比较小众,不处理其实也OK的

**Comment by lkiuyu** [comment]
我打算回归最朴素的正则了，换回\b[A-Za-z0-9]{4,7}\b
最开是设计的时候就是使用的这个正则，但是发现一旦收到类似uc网盘这种短信
【UC优视】**验证码8415**，用于登录。泄露有风险，如非本人操作，请忽略本条短信。
这种验证码和数字紧密连在一块的，程序用最开始的正则就筛选不出来了，所以后面才改改改改成现在程序里的那种
现在我准备直接程序里处理，碰到验证码关键词的，我直接在短信内容里把关键词两边价个空格，这样就可以提取了

**Comment by lkiuyu** [comment]
已更新，可以试试最新的，我特地手动把你那条京东短信发了一遍，测试提取没问题了

**Comment by Cxleos** [comment]
已经尝试最新版,验证码获取正常,大佬666
