### ISSUE TITLE
-bash: ./DbusSmsForward: cannot execute: required file not found

### ISSUE THREAD

**Issue by luqizhi666** [lkiuyu/DbusSmsForward#9]
-bash: ./DbusSmsForward: cannot execute: required file not found

**Comment by lkiuyu** [comment]
你的描述内容过于笼统，我这也看不出你具体是什么问题情况，我建议你使用我另一个项目DbusSmsForwardCPlus，这个项目的readme有具体的使用方法，功能方面涵盖了这个项目的所有功能并添加了新的功能

**Comment by luqizhi666** [comment]
好的谢谢
